sudo : false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
#  - "pypy"
#  - "pypy3"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      - build-essential

before_install:

 - pip install --upgrade pip

install:
 - pip install -qq flake8
 - pip install .

script:
  - nosetests --verbosity=2 --with-doctest
  - flake8 --version
  - flake8 --ignore E501 morse_talk

notifications:
  email: false
